kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: guestbook-ui-ing
  annotations:
    traefik.ingress.kubernetes.io/rewrite-target: /guestbook
spec:
  rules:
    - http:
        paths:
          - path: /guestbook
            backend:
              serviceName: guestbook-ui
              servicePort: 8092
