apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
annotations:
  traefik.ingress.kubernetes.io/rewrite-target: /guestbook
spec:
  type: LoadBalancer
  ports:
  - port: 8092
    targetPort: 80
  selector:
    app: guestbook-ui
