kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: guestbook-ui-ing
  annotations:
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: guestbook.latnomis.com
      http:
        paths:
          - path: /
            backend:
              serviceName: guestbook-ui
              servicePort: 8092
